### ISSUE TITLE
Don't `impl Display` if it already implemented for a type

### ISSUE THREAD

**Issue by Oakchris1955** [dtolnay/thiserror#305]
If a struct/enum already implements the `Display` trait, using the `thiserror::Error` macro creates an impl conflict. This can be a common problem in empty structs/enums, as `thiserror::Error` will implement the `Display` trait for them. It also becomes a serious problem if someone uses other derive macro crates, such as `displaydoc`, which follow a similar behavior.

**Comment by dtolnay** [comment]
I think this is all right as currently implemented. As the readme says, thiserror only produces the Display impl if the struct or enum has #\[error("...")\] attributes. You can leave our that attribute and not get a Display impl generated by thiserror. If your issue is some other derive macro looking at that same "error" attribute, then I would recommend not using that other macro together with thiserror.

**Comment by dtolnay** [comment]
> This can be a common problem in empty structs/enums, as `thiserror::Error` will implement the `Display` trait for them.

From checking the code and trying `cargo expand`, I don't think this applies to empty structs.

For empty enums, there is a vacuous case of "every variant is transparent" so you do unconditionally get a Display impl. But for empty enums, thiserror is not really providing value and you might as well write the 1-line Error impl instead of deriving it.

```rust
impl std::error::Error for MyEmptyEnum {}
```
