### ISSUE TITLE
Figure out what to do about void enums

### ISSUE THREAD

**Issue by dtolnay** [dtolnay/thiserror#5]
We should have some way to have derive(Error) emit a Display impl for a void enum; I don't think it works currently. Specifically, for enums the macro looks for at least one variant that has a `#[error("...")]` attribute to decide whether to generate Display, and void enums don't have any variants.

```rust
#[derive(Debug, Error)]
pub enum Error {}
```

Maybe the following should generate a Display impl, but it seems a bit silly because the message is meaningless as the Display impl is unreachable.

```rust
#[derive(Debug, Error)]
#[error("...")]
pub enum Error {}
```

**Comment by Jezza** [comment]
The display impl in itself is a bit weird, but I think the benefit might come from it being a placeholder.  
Much for the same reason the Error has no variants, it could be that it's just not been populated yet.  

I know I've created an empty Error enum before, because I want the compiler to scream at me which of the `From<_>` impls I need.
